# Generated by Django 4.1.1 on 2022-09-24 05:03

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(max_length=255)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('expired_at', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('state', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
            ],
            options={
                'verbose_name': 'Email Verification',
                'verbose_name_plural': 'Email Verifications',
                'db_table': 'verification_service_email',
            },
        ),
        migrations.CreateModel(
            name='SMSVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(max_length=255)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('expired_at', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('state', models.CharField(max_length=128)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone number')),
            ],
            options={
                'verbose_name': 'SMS Verification',
                'verbose_name_plural': 'SMS Verifications',
                'db_table': 'verification_service_sms',
                'ordering': ('-id',),
            },
        ),
    ]
