# Generated by Django 4.1.1 on 2022-09-24 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverification',
            old_name='state',
            new_name='signature',
        ),
        migrations.RenameField(
            model_name='smsverification',
            old_name='state',
            new_name='signature',
        ),
    ]
