# Generated by Django 4.1.1 on 2022-11-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification_service', '0002_rename_state_emailverification_verification_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='active',
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='smsverification',
            name='active',
        ),
        migrations.RemoveField(
            model_name='smsverification',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='code_sent_successfully',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smsverification',
            name='code_sent_successfully',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='email',
            field=models.EmailField(max_length=1024, verbose_name='Email'),
        ),
    ]
