# Generated by Django 4.1.1 on 2023-01-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification_service', '0003_remove_emailverification_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
        migrations.DeleteModel(
            name='SMSVerification',
        ),
    ]
